name: Update pattern library

on:
  workflow_dispatch:

jobs:
  update-patterns:
    name: Update pattern library
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          ref: auto-pull-pattern-updates
          submodules: true

      - name: Read node version from .nvmrc
        id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1

      - uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvmrc.outputs.node_version }}"

      - uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm ci

      - name: Run linter
        run: npm run lint
        continue-on-error: false

      - name: Update pattern submodule
        run: git submodule update --init --remote --merge

      - name: Add and commit any changes
        uses: EndBug/add-and-commit@v5
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: "dots-patterns"

          # The name of the user that will be displayed as the author of the commit
          # Default: author of the commit that triggered the run
          author_name: DOTS Community

          # The email of the user that will be displayed as the author of the commit
          # Default: author of the commit that triggered the run
          author_email: no-reply@decentpatterns.xyz

          # Name of the branch to use, if different from the one that triggered the workflow
          # Default: the branch that triggered the run
          branch: master

          # The message for the commit
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: "Update pattern library"

          # Whether to use the --signoff option on `git commit` (only `true` and `false` are accepted)
          # Default: false
          signoff: true

        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
